### PR TITLE
Add Moby Thesaurus backend

### PR DESCRIPTION
**Pull request by mattbeshara**
Hi there, I've written a backend which allows you to use the Moby thesaurus, which I find gives better results than WordNet.  The Moby thesaurus is public domain and available from many sources online, including Project Gutenberg: https://www.gutenberg.org/files/3202/files/
Let me know what you think!

### CODE REVIEW

**Comment by hpdeifel** [comment]
Sounds good. I'll be sure to take a detailed look soon. Might take a few days, though

**Comment by mattbeshara** [comment]
Hey, I've just pushed another couple of commits which address a couple of minor potential bugs.  Have you had time to look at the code yet?

**Comment by hpdeifel** [comment]
Thanks! Unfortunately, the "few days" still drag on a bit, sorry.

**Comment by mattbeshara** [comment]
Would you have any objections to me closing this PR and releasing my code separately?

**Comment by mattbeshara** [comment]
For anyone who may be interested, I've put this code up at https://git.sr.ht/~mfa/synosaurus-moby

**Pull request closed without merging**
